name: GrizzlyEnchants
authors: [ Couph ]
depend: [GrizzlyTools, GrizzlyBackpacks, WorldGuard, WorldEdit]
softdepend: [PlaceholderAPI]
version: '1.1-SNAPSHOT'
main: me.couph.grizzlyenchants.GrizzlyEnchants
description: Custom Enchants for play.grizzlyprison.com
website: grizzlyprison.com
commands:
  ge:
    usage: /<command>
    description: Enchants command.
    aliases: [grizzlyenchants]
  enchants:
    usage: /<command>
    description: Opens enchants GUI.
    aliases: [ench, enchant]
  tokenshop:
    usage: /<command>
    description: Open the token shop.
    aliases: [tshop]
  token:
    usage: /<command>
    description: Token command.
    aliases: [tokens]
  top:
    usage: /<command>
    description: Teleport to the top of the mine.
    aliases: []
  withdrawtokens:
    usage: /<command>
    description: Withdraw tokens.
    aliases: [tokenwithdraw, withdrawtoken, tokenswithdraw, shard]
  tinkerer:
    usage: /<command>
    description: Tinkerer/Disenchanter
    aliases: [disenchant, disenchanter, tinker]
  enchanter:
    usage: /<command>
    description: Open pickaxe enchanter
    aliases: [pickaxe, menu]